### ISSUE TITLE
[Question] Seek distance and script request etc

### ISSUE THREAD

**Issue by DesolatePsyche** [Moodkiller/MPV-Made-Easy#3]
Hi, have few questions.

How change default seek distance? Right know left-right arrow skips by 10 seconds. I would like to reduce it to 5 seconds.
I tried adding to input.cfg
`Shift+RIGHT seek  3 exact
Shift+LEFT  seek -3 exact`
But it didn't work.

2. Can we have subtitle search function with UI. Similar to MPC-HC D button that searched for subs. For MPV I see there is something called sublime, which I failed to set up.
I attempted to set up sublime with this script " https://github.com/vayan/autosub-mpv/blob/master/autosub.lua " , but alas. Once again. It didn't work.  It's useful feature to have if watching movies/series that don't have subs included. So would nice to have. Convenience feature to avoid dl'ing subs from web.

I know there are bunch of scripts for sub search, automatic sub search and dl(+ones that use sublime and ones that use other places) and sub search with GUI etc.. but somehow I keep failing at setting them up.

3. Playing YouTube stuff.
Well, not even sure what to say here. I get this sort of screen/error when attempting to play anything from youtube. https://i.imgur.com/QOnkpW6.png

(4.) Just extra question. Is MVP interlace feature essentially SVP?
(5.) Method of play-next-video in the folder? Without having to drag whole folder onto MPV to create playlist.

**Comment by Moodkiller** [comment]
Hi there, sorry for the late reply to this...

1. The seek setting within the `mpv_thumbnail_script_client_osc.lua` script defines the seeking amounts. The easiest solution, use `shift+left/right` to seek by 1 second (hold the combination to seek faster but not in massive sections at a time). 
2. Personally, I am against subtitle databases as they just seem to be a massive pool of what ever is around and matches the current videos title. Depending what you are watching, I would source the subtitles from somewhere like Animetosho and drop them into the same folder as the video you are watching. The `mpv.conf` is set to look for subtitles within the videos directory to use during playback. Also, did you have a look at this: https://www.reddit.com/r/Python/comments/425cvn/how_to_run_subliminal_in_windows/
3. If you want the video to play in mpv, comment out this line: [ytdl-format=bestaudio](https://github.com/Moodkiller/MPV-Made-Easy/blob/master/mpv/mpv.conf#L72). The other thing I suggest is to always make sure youtube-dl is up to date by running the `updater.bat` script.
4. That I am not sure of to be honest, apologies!
5. Fixed with commit bcdde9a8f63531e87d3cba317fd5b03f3f1bc79f: It will autoload the files when you add them now OR if you alter the folder afterwards, then `shift+p`.
